# Generated by Django 4.0.4 on 2023-03-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_head', models.CharField(max_length=40)),
                ('b_body', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
